proto_library(
  name = "cell_proxy_common_proto",
  srcs = [
    "cell_proxy_common.proto",
  ],
)
proto_library(
  name = "futures_service_proto",
  srcs = [
    "futures_service.proto",
  ],
  deps = [
    ":cell_proxy_common_proto",
  ]
)
proto_library(
  name = "push_service_proto",
  srcs = [
    "push_service.proto",
  ],
  deps = [
    ":cell_proxy_common_proto",
  ]
)

