cc_library (
name = "futures_common",
  srcs = [
    "common.cc",
    "md5.cc"
  ],
  deps = [
    "//futures_cell_proxy/proto:futures_service_proto",
    "//thirdparty/cryptopp:cryptopp",
    "//thirdparty/glog:glog",
    "//thirdparty/gflags:gflags",
    "#pthread",
    "#rt",
    "#idn",
    "#libz",
    "#curl",
    "#z"
  ],
)
